import type { BookmarkNode } from "@/types";

export const MOCK_BOOKMARKS: BookmarkNode[] = [
  {
    type: "folder",
    id: "1",
    title: "Bookmarks Bar",
    children: [
      {
        type: "folder",
        id: "10",
        title: "Dev Tools",
        parentId: "1",
        children: [
          {
            type: "link",
            id: "100",
            title: "GitHub",
            url: "https://github.com",
            parentId: "10",
          },
          {
            type: "link",
            id: "101",
            title: "Stack Overflow",
            url: "https://stackoverflow.com",
            parentId: "10",
          },
          {
            type: "link",
            id: "102",
            title: "MDN Web Docs",
            url: "https://developer.mozilla.org",
            parentId: "10",
          },
          {
            type: "link",
            id: "103",
            title: "TypeScript",
            url: "https://www.typescriptlang.org",
            parentId: "10",
          },
        ],
      },
      {
        type: "folder",
        id: "11",
        title: "Design",
        parentId: "1",
        children: [
          {
            type: "link",
            id: "110",
            title: "Figma",
            url: "https://figma.com",
            parentId: "11",
          },
          {
            type: "link",
            id: "111",
            title: "shadcn/ui",
            url: "https://ui.shadcn.com",
            parentId: "11",
          },
          {
            type: "link",
            id: "112",
            title: "Tailwind CSS",
            url: "https://tailwindcss.com",
            parentId: "11",
          },
          {
            type: "link",
            id: "113",
            title: "Dribbble",
            url: "https://dribbble.com",
            parentId: "11",
          },
        ],
      },
      {
        type: "folder",
        id: "12",
        title: "AI Tools",
        parentId: "1",
        children: [
          {
            type: "link",
            id: "120",
            title: "ChatGPT",
            url: "https://chat.openai.com",
            parentId: "12",
          },
          {
            type: "link",
            id: "121",
            title: "Claude",
            url: "https://claude.ai",
            parentId: "12",
          },
          {
            type: "link",
            id: "122",
            title: "Perplexity",
            url: "https://perplexity.ai",
            parentId: "12",
          },
          {
            type: "link",
            id: "123",
            title: "Gemini",
            url: "https://gemini.google.com",
            parentId: "12",
          },
          {
            type: "link",
            id: "124",
            title: "Hugging Face",
            url: "https://huggingface.co",
            parentId: "12",
          },
          {
            type: "link",
            id: "125",
            title: "Midjourney",
            url: "https://www.midjourney.com",
            parentId: "12",
          },
          {
            type: "link",
            id: "126",
            title: "Replicate",
            url: "https://replicate.com",
            parentId: "12",
          },
          {
            type: "link",
            id: "127",
            title: "Poe",
            url: "https://poe.com",
            parentId: "12",
          },
        ],
      },
      {
        type: "link",
        id: "18",
        title: "Product Hunt",
        url: "https://www.producthunt.com/",
        parentId: "1",
      },
      {
        type: "link",
        id: "13",
        title: "Google",
        url: "https://google.com",
        parentId: "1",
      },
      {
        type: "link",
        id: "14",
        title: "YouTube",
        url: "https://youtube.com",
        parentId: "1",
      },
      {
        type: "link",
        id: "17",
        title: "Medium",
        url: "https://medium.com/",
        parentId: "1",
      },
      {
        type: "link",
        id: "25",
        title: "Bilibili",
        url: "https://www.bilibili.com/",
        parentId: "1",
      },
      {
        type: "link",
        id: "15",
        title: "Behance",
        url: "https://behance.net/",
        parentId: "1",
      },
      {
        type: "link",
        id: "30",
        title: "Gmail",
        url: "https://mail.google.com/",
        parentId: "1",
      },
      {
        type: "link",
        id: "16",
        title: "Pinterest",
        url: "https://www.pinterest.com/",
        parentId: "1",
      },
      {
        type: "link",
        id: "29",
        title: "Notion",
        url: "https://www.notion.so/",
        parentId: "1",
      },
      {
        type: "link",
        id: "19",
        title: "ZCOOL",
        url: "http://www.zcool.com.cn/",
        parentId: "1",
      },
      {
        type: "link",
        id: "28",
        title: "X",
        url: "https://x.com/",
        parentId: "1",
      },
    ],
  },
  {
    type: "folder",
    id: "2",
    title: "Other Bookmarks",
    children: [
      {
        type: "link",
        id: "200",
        title: "Hacker News",
        url: "https://news.ycombinator.com",
        parentId: "2",
      },
      {
        type: "link",
        id: "201",
        title: "Reddit",
        url: "https://reddit.com",
        parentId: "2",
      },
      {
        type: "folder",
        id: "20",
        title: "Reading List",
        parentId: "2",
        children: [
          {
            type: "link",
            id: "202",
            title: "The Morning Paper",
            url: "https://blog.acolyer.org",
            parentId: "20",
          },
          {
            type: "link",
            id: "203",
            title: "Overreacted",
            url: "https://overreacted.io",
            parentId: "20",
          },
        ],
      },
      {
        type: "folder",
        id: "21",
        title: "Shopping",
        parentId: "2",
        children: [
          {
            type: "link",
            id: "210",
            title: "Amazon",
            url: "https://amazon.com",
            parentId: "21",
          },
        ],
      },
    ],
  },
];
